### PR TITLE
Enable couples of optimizations for C#

### PR DESCRIPTION
**Pull request by hez2010**
- Disable useless features.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
This is breaking the rules: https://github.com/MichalStrehovsky/sizegame#rules

**Comment by hez2010** [comment]
But isn't `You can enable optimizations if optimizations are not enabled by default.`?

**Comment by MichalStrehovsky** [comment]
That's just a concession to compilers that don't optimize by default. "If the compiler has a master switch "enable optimizations", that switch should be used". We use that. Release is the default in .net 8.

**Comment by hez2010** [comment]
Closing this PR as rules violation.

**Pull request closed without merging**
